global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gradio_app'
    metrics_path: /
    static_configs:
      - targets: ['172.18.0.20:8000']  # Gradio metrics

  - job_name: 'node_exporter_gradio'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.18.0.20:9100']  # Node Exporter
